services:
  app:
    build: ./app/
    container_name: messenger_app
    environment:
      - DISPLAY=$DISPLAY
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    ports:
      - "5000:5000"
    tty: true
    depends_on:
      - sqlserver
  sqlserver:
    build: ./database/
    container_name: sqlserver_container
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=WeHacking808
      - MSSQL_TRUST_SERVER_CERTIFICATE=YES
    volumes:
      - ./database:/tmp
      - sqlserver_data:/var/opt/mssql
    user: root
    command: /tmp/start.sh
    tty: true

volumes:
  sqlserver_data:
    driver: local

networks:
  default:
    driver: bridge
