services:
  app:
    build: ./app/
    container_name: messenger_app
    environment:
      - DISPLAY=$DISPLAY
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    ports:
      - "5000:5000"
    tty: true
    depends_on:
      - sqlserver
    networks:
      default:
        ipv4_address: 172.0.0.2
    command: python gui.py

  sqlserver:
    build: ./database/
    container_name: sqlserver_container
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=WeHacking808
      - MSSQL_TRUST_SERVER_CERTIFICATE=YES
    volumes:
      - ./database:/tmp
      - sqlserver_data:/var/opt/mssql
    user: root
    command: /tmp/start.sh
    tty: true
    networks:
      default:
        ipv4_address: 172.0.0.3

  test_app_1:
    build: ./test_node_1/
    container_name: test_app_1_container
    tty: true
    depends_on:
      - test_sqlserver_1
    profiles:
      - testing
    networks:
      default:
        ipv4_address: 172.0.0.4
    command: python messenger.py

  test_sqlserver_1:
    build: ./database/
    container_name: test_sqlserver_1_container
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=WeHacking808
      - MSSQL_TRUST_SERVER_CERTIFICATE=YES
    volumes:
      - ./database:/tmp
      - ./test_node_1/test_data:/var/opt/mssql
    user: root
    command: /tmp/start.sh
    tty: true
    profiles:
      - testing
    networks:
      default:
        ipv4_address: 172.0.0.5

  test_app_2:
    build: ./test_node_2/
    container_name: test_app_2_container
    tty: true
    depends_on:
      - test_sqlserver_2
    profiles:
      - testing
    networks:
      default:
        ipv4_address: 172.0.0.6
    command: python messenger.py

  test_sqlserver_2:
    build: ./database/
    container_name: test_sqlserver_2_container
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=WeHacking808
      - MSSQL_TRUST_SERVER_CERTIFICATE=YES
    volumes:
      - ./database:/tmp
      - ./test_node_2/test_data:/var/opt/mssql
    user: root
    command: /tmp/start.sh
    tty: true
    profiles:
      - testing
    networks:
      default:
        ipv4_address: 172.0.0.7

volumes:
  sqlserver_data:
    driver: local

networks:
  default:
    driver: bridge
    ipam:
      config:
      - subnet: 172.0.0.0/24
